name: Check aiven services

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *" # daily, 5am

    

permissions:
  contents: write       # required for pushing commits
  pull-requests: write  # required for merging PRs

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7
        with:
          ref: master

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Cache pip
        uses: actions/cache@v6
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        id: run_py_script
        env:
          NOT_DOTENV: ${{ vars.NOT_DOTENV }}
          LOG_LEVEL: ${{ vars.LOG_LEVEL }}
        run: |
          python main.py --access
